---
version: "3.3"

# Here you defines the servers and the networks to communicate with the boards

services:
  # Http servers to upload new firmwares
  http:
    image: httpd:2.4
    volumes:
      -  $PWD/docker-local-files/volume/http-root:/usr/local/apache2/htdocs/
    networks:
      lan:
        ipv4_address: ${HTTP_LANIP}
      netio:
    ports:
      - 8080:80

networks:
  lan:
    driver: macvlan
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
    driver_opts:
      parent: eth2.2
      gateway: 192.168.0.1
      opt: "macvlan_mode=bridge"

  netio:
    driver: macvlan
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24
    driver_opts:
      parent: eth2.5
      gateway: 192.168.2.78
      opt: "macvlan_mode=bridge"

