---
    version: "3.3"

    services:
      test:
        image: e2e_tests
        build: e2e_tests
        hostname: ${GTW_SERIALNUM}_e2e
        command: bash -c "arp -s ${GTW_LANIP} ${GTW_MACADDR} && bash"
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        privileged: true
        volumes:
          - $PWD/docker-local-files/volume/${GTW_SERIALNUM}:/opt/workdir/tests/reports/:rw
        networks:
          - ${GTW_NETWORK}
          - netio

    networks:
      gtw-lan0:
          name: gtw-lan0
          external: true
      gtw-lan1:
          name: gtw-lan1
          external: true
      netio:
          name: netio
          external: true
